Portfolio project (desktop version)
teke85/mobileFirst_portfolioSetup pull request #5
Opened 2022-08-26 18:14 UTC by teke85

### This Pull Request is based on the Desktop Version Portfolio Project requirement and it fulfils the following objectives.

# General requirements

- To make sure that there are no linter errors.
- To make sure that correct GitHub Flow is used.
- Make sure that work is documented in a professional way.

# Project requirements

- To build a Desktop Version of the Portfolio similar to the one provided in the figma design.
- To use media queries in the CSS file to make the desktop version.
- To use Grid and Flexbox to layout elements on the page.
- Adding JavaScript functionality is not required.
- To replicate the figma design as much as possible.

# Screenshot of Complete Project
![Portfolio](https://user-images.githubusercontent.com/29442846/186966438-4e4d45b8-ef56-43ce-b55d-db7fe373f546.jpg)

2022-08-26 19:30 UTC, mugishasam123 requested changes
Hi team  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors 👍 
- Nice use of git-flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 19:30 UTC, mugishasam123 commented on index.html
> +            </li>
- [ ] Kindly stick to the design as much as possible to make it match the Figma design.that will make your project look more professional. you got this 👍 

Figma design:
![image](https://user-images.githubusercontent.com/90524466/186976323-797e5937-9f37-42c2-945a-959f7cdd755c.png)


Your design:
![image](https://user-images.githubusercontent.com/90524466/186976431-0e9d5ac8-0005-44de-b6d6-3fa6ac0a069f.png)

2022-08-26 19:30 UTC, mugishasam123 commented on index.html
> +          </div>
- [ ] Please try to stick to the design as much as possible to make your work match the Figma design .and that will make your work more professional. you can do so by leveraging colors, font size, padding, etc.

Figma design:
![image](https://user-images.githubusercontent.com/90524466/186977121-4eadeb06-7cd6-4f6f-9053-07c9510e8a71.png)

Your design:
![image](https://user-images.githubusercontent.com/90524466/186977186-204906e8-ab9c-4b74-bdf5-26e1a9c81679.png)

2022-08-27 07:16 UTC, teke85 commented on index.html
> +          </div>
Hi @mugishasam123 Thank you very much for your awesome feedback. I have made some changes and this is how my project looks now. 
![Applied Changes (1)](https://user-images.githubusercontent.com/29442846/187019564-b03d2dcd-6e8c-4deb-bead-978e22387f26.jpg)

2022-08-27 07:30 UTC, teke85 commented on index.html
> +            </li>
@mugishasam123 Thank you so much for your professional feedback. I have made changes and this is how my project looks now.

![Portfolio (2)](https://user-images.githubusercontent.com/29442846/187020028-e1278746-0ab8-4556-9327-7ee9d680e6fa.jpg)

2022-08-27 13:11 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @teke85 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing all the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design and animations ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 13:11 UTC, awais-amjed commented on index.html
> +    <section id="about" class="about-section">
[OPTIONAL] It would be nice to introduce some margin around the about Myself section as shown in the Figma Design 🤗

Your design:
![image](https://user-images.githubusercontent.com/73714615/187031734-e6316393-c705-4cf1-b651-143fd223c29f.png)

Figma design:
![image](https://user-images.githubusercontent.com/73714615/187031739-2b6db4c9-4d85-4a92-aa3c-884f288ef15c.png)

2022-08-27 13:28 UTC, teke85 commented on index.html
> +    <section id="about" class="about-section">
Hi @awais-amjed Thank you for taking time to review my project. I will apply the necessary changes. 🙏🏽

2022-08-27 13:29 UTC, merged